### ISSUE TITLE
Add the merge strategy variant

### ISSUE THREAD

**Issue by klauskpm** [survivejs/webpack-merge#99] opened 2018-03-20 17:38 UTC
Create a strategy variant as prepend, append and replace, for merge.

### Configuration objects used
```js
// webpack.config.dev.js
{
  "entry": {
    "main": ["./src\\config\\main.ts"],
    "polyfills": ["./src\\config\\polyfills.ts"],
    "styles": ["./src\\assets\\styles\\styles.sass"]
  },
}

// webpack.config.playground.js
{
  "entry": {
    "main": ["./src\\config\\main.playground.ts"]
  },
}
```

### Observed behaviour
I used all 3 strategies(prepend, append and replace) to merge the **dev** configuration with the **playground** configuration  and they gave me these results:
```js
// prepend
{
  main: [
    './src\\config\\main.playground.ts',
    './src\\config\\main.ts'
  ],
  polyfills: ['./src\\config\\polyfills.ts'],
  styles: ['./src\\assets\\styles\\styles.sass']
}

// append
{
  main: [
    './src\\config\\main.ts',
    './src\\config\\main.playground.ts'
  ],
  polyfills: ['./src\\config\\polyfills.ts'],
  styles: ['./src\\assets\\styles\\styles.sass']
}

// replace
{
  main: ['./src\\config\\main.playground.ts']
}
```

### Desired behaviour
Instead of creating a `customizaObject` to merge, it would be better to have it internaly. The expected result from the merge would be this:
```js
// merge
{
  main: ['./src\\config\\main.playground.ts'],
  polyfills: ['./src\\config\\polyfills.ts'],
  styles: ['./src\\assets\\styles\\styles.sass']
}
```

I achieved the above result creating the following `customizeObject`:
```js
var webpackMerge = require('webpack-merge');
var webDev = require('./webpack.config.dev')();
var mergeStrategy = {
    customizeObject(a, b, key) {
        if (key === 'entry') {
            return Object.assign({}, a, b);
        }

        return undefined;
    }
};
var webpackPlaygroundMerge = webpackMerge(mergeStrategy);

module.exports = webpackPlaygroundMerge(webDev, {
    "entry": {
        "main": [
            "./src\\config\\main.playground.ts"
        ]
    }
});
```

**Comment by chinesedfan** [comment] 2019-11-02 11:09
A easier way is to set strategy for the specified key. But if there are too many keys under `entry`, you need as many rule as well.

```
const mergedConfig = webpackMerge.strategy({
  'entry.main': 'replace',
  'entry.polyfills': 'replace',
  'entry.styles': 'replace',
})(a, b)
```

The problem is that current `key: strategy` design only controls how the key itself be merged. Maybe we can add 3 new strategy called `replaceChildren/prependChildren/appendChildren`. Then we can achieve above result by a single key.

```
const mergedConfig = webpackMerge.strategy({
  'entry': 'replaceChildren',
})(a, b)
```

But it will make things more complicated. In fact, I am not very like it. What do you guys think? (cc @bebraw)

**Comment by bebraw** [comment] 2020-07-03 12:49
I will add support for wildcards in v5 (#135). Thanks for the idea and examples.

**Closed** 2020-07-03 15:06 UTC
