### ISSUE TITLE
TypeError: Merging undefined is not supported

### ISSUE THREAD

**Issue by angeloh** [survivejs/webpack-merge#190] opened 2021-07-06 11:23 UTC
I got this error when running $ quasar dev on my Vue project

```
~/project/node_modules/webpack-merge/dist/index.js:63
            throw new TypeError("Merging undefined is not supported");
                  ^

[  TypeError: Merging undefined is not supported

  - index.js:63 mergeWithOptions
    [project]/[webpack-merge]/dist/index.js:63:19

  - index.js:52 merge
    [project]/[webpack-merge]/dist/index.js:52:35

  - quasar-conf-file.js:392 QuasarConfFile.compile
    [project]/[@quasar]/app/lib/quasar-conf-file.js:392:29

  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5

  - quasar-dev:237 async goLive
    [project]/[@quasar]/app/bin/quasar-dev:237:3

].
```

**Comment by angelorobo** [comment] 2021-07-06 11:24
Up

**Comment by bebraw** [comment] 2021-07-06 11:27
Can you paste the merge you are trying to perform? Essentially the error means that there's something like this: `merge({ ... }, undefined)`. To fix, there shouldn't be `undefined` in the parameters and it's better to filter it out.

It's like this by design so I'm closing the issue as `wontfix`.

**Comment by bebraw** [comment] 2021-07-06 11:28
Given the issue is coming from quasar, it may be worth re-opening the issue with a repository they can examine there.

**Closed by bebraw** 2021-07-06 11:27 UTC

**Comment by angelorobo** [comment] 2021-07-06 11:29
Okay thanks! @bebraw
