### ISSUE TITLE
Error when trying to merge when `use` type is `function`

### ISSUE THREAD

**Issue by anshulguleria** [survivejs/webpack-merge#127] opened 2020-04-08 07:41 UTC
1. Check the version of **webpack-merge** you are using. If it's not the newest version, update and try again (see changelog while updating!). __4.1.4__
2. If the issue is still there, write a minimal script showing the problem and expected output. You can also set up a repository (even better).
3. Include the script to the issue. Mention Node version(__Node 12__) and OS in your report.

I am using webpack merge to merge my common configuration to my dev configuration.

In my common block I am adding rule for svg which uses `use` block as an array. Example:

```javascript
{
         test: /\.svg$/,
         use: [
           {
             loader: require.resolve("url-loader"),
             options: {
               // some options
             },
           },
         ]
}
```

In my dev file I wanted to override it and wanted to use `function` signature of `use` section. This documented [here](https://webpack.js.org/configuration/module/#ruleuse)

My code example:

```javascript
{
         test: /\.svg$/,
         use: function (info) {
             return [
                 { loader: "babel-loader", }
                 {
                     loader: require.resolve("react-svg-loader"),
                     options: {
                         // some options
                     },
                 },
              ];
         }
}
```

I expect my final output to be the one containing the function and completely remove the older one.

Merge strategy: "smart"

But current code doesn't understand the `function` data type yet. And is raising error when trying to merge arrays smartly.

> Note: I am using function because I wanted to override not merge this specific section. And I can't change the merge strategy because I need loaders merging in other blocks of my configuration.

**Comment by onetrev** [comment] 2020-06-02 05:08
I think this is probably a duplicate of [this issue](https://github.com/survivejs/webpack-merge/issues/89).

**Comment by anshulguleria** [comment] 2020-06-03 05:09
I think this is different as the issue you mentioned @onetrev is for enabling the input configuration as function but, this is about allowing the `use` property in rules to be a method.

**Comment by bebraw** [comment] 2020-07-03 11:54
I'll drop the support for smart merging in v5 (see #135) as there are lots of corner cases like this that aren't easy to support. The recommendation is to move to use the regular merge function and then use the utilities included for anything special.

**Closed** 2020-07-03 15:06 UTC
